### PR TITLE
Lesson 3

### PR DESCRIPTION
**Pull request by IharDorinel**

### CODE REVIEW

**Comment by romos21** [comment]
@IharDorinel Great! But you forgot to close FORM tag - as an answer on one of test's questions - browser made it for you and you didn't catch this error =)

**Comment by IharDorinel** [comment]
> @IharDorinel Great! But you forgot to close FORM tag - as an answer on one of test's questions - browser made it for you and you didn't catch this error =)

Ok, and now I have done it.

**Comment by romos21** [comment]
> > @IharDorinel Great! But you forgot to close FORM tag - as an answer on one of test's questions - browser made it for you and you didn't catch this error =)
> 
> Ok, and now I have done it.

@IharDorinel ok - but commit and push your changes ,  it's bad idea to merge it with mistake

**Comment by romos21** [comment]
@IharDorinel Merged it!

**Comment by IharDorinel** [comment]
> > > @IharDorinel Great! But you forgot to close FORM tag - as an answer on one of test's questions - browser made it for you and you didn't catch this error =)
> > 
> > 
> > Ok, and now I have done it.
> 
> @IharDorinel ok - but commit and push your changes , it's bad idea to merge it with mistake

@romos21

**Pull request merged**
